# Generated by Django 4.2 on 2025-04-06 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
