# Generated by Django 4.2 on 2025-04-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_total_sale_total_price_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(),
        ),
    ]
